name: area-prod
services:
  client_mobile:
    image: ghcr.io/epitouche/area-mobile:dev
    extends:
      file: ./docker-compose.template.yaml
      service: client_mobile

  client_web:
    image: ghcr.io/epitouche/area-frontend:dev
    labels:
      - "traefik.http.routers.client_web.rule=Host(`tom-mendy.com`)"
      - "traefik.http.routers.client_web.entrypoints=websecure"
      - "traefik.http.routers.client_web.tls.certresolver=myresolver"
    extends:
      file: ./docker-compose.template.yaml
      service: client_web

  database:
    extends:
      file: ./docker-compose.template.yaml
      service: database

  reverse-proxy:
    volumes:
      - letsencrypt:/letsencrypt
    labels:
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tom.mendy@tom-mendy.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    extends:
      file: ./docker-compose.template.yaml
      service: reverse-proxy

  server:
    image: ghcr.io/epitouche/area-backend:dev
    extends:
      file: ./docker-compose.template.yaml
      service: server

  server-documentation:
    image: ghcr.io/epitouche/area-backend-documentation:dev
    extends:
      file: ./docker-compose.template.yaml
      service: server-documentation

networks:
  app-networks:


volumes:
  database-data:
  shared_apk:
  letsencrypt:
