name: area-prod
services:
  client_mobile:
    build:
      context: ./mobile
      target: build-apk
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: client_mobile

  client_web:
    build:
      context: ./frontend
      target: run
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: client_web

  database:
    extends:
      file: ./docker-compose.template.yaml
      service: database

  server:
    build:
      context: ./backend
      target: run
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: server

networks:
  app-networks:


volumes:
  database-data:
  shared_apk:
