services:
  server:
    container_name: server
    build:
      target: run
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    networks:
      - app-networks
    ports:
      - "8080:8080"
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/about.json"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  client_mobile:
    container_name: client_mobile
    build:
      target: build-apk
      dockerfile: mobile/Dockerfile
    volumes:
      - shared_apk:/app/public/apk
    networks:
      - app-networks

  client_web:
    container_name: client_web
    build:
      target: run
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - shared_apk:/app/public/apk
    networks:
      - app-networks
    depends_on:
      - server
      - client_mobile

  database:
    image: postgres:13
    container_name: database
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - app-networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d area-database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database-data:
  shared_apk:

networks:
  app-networks:
