name: area-prod
services:
  client_mobile:
    image: ghcr.io/epitouche/area-mobile:main
    extends:
      file: ./docker-compose.template.yaml
      service: client_mobile

  client_web:
    image: ghcr.io/epitouche/area-frontend:main
    labels:
      - "traefik.http.routers.client_web.rule=Host(`tom-mendy.com`)"
      - "traefik.http.routers.client_web.entrypoints=websecure"
      - "traefik.http.routers.client_web.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    extends:
      file: ./docker-compose.template.yaml
      service: client_web

  database:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    extends:
      file: ./docker-compose.template.yaml
      service: database

  reverse-proxy:
    volumes:
      - letsencrypt:/letsencrypt
    labels:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tom.mendy@tom-mendy.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    extends:
      file: ./docker-compose.template.yaml
      service: reverse-proxy

  server:
    image: ghcr.io/epitouche/area-backend:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    extends:
      file: ./docker-compose.template.yaml
      service: server

  server-documentation:
    image: ghcr.io/epitouche/area-backend-documentation:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    extends:
      file: ./docker-compose.template.yaml
      service: server-documentation

  watchtower:
    image: containrrr/watchtower:1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"

networks:
  app-networks:


volumes:
  database-data:
  shared_apk:
  letsencrypt:
