name: area-prod
services:
  client_mobile:
    build:
      context: ./mobile
      target: build-apk
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: client_mobile

  client_web:
    build:
      context: ./frontend
      target: run
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: client_web
    labels:
      - "traefik.http.routers.client_web.rule=Host(`localhost`)"


  database:
    extends:
      file: ./docker-compose.template.yaml
      service: database

  server:
    build:
      context: ./backend
      target: run
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: server

  reverse-proxy:
    extends:
      file: ./docker-compose.template.yaml
      service: reverse-proxy

  server-documentation:
    build:
      context: ./backend
      target: documentation
      dockerfile: Dockerfile
    extends:
      file: ./docker-compose.template.yaml
      service: server-documentation

networks:
  app-networks:


volumes:
  database-data:
  shared_apk:
