services:
  backend-go:
    container_name: backend-go
    build:
      target: run
      dockerfile: backend/go/Dockerfile
    ports:
      - "8080:8080"

  backend-java:
    container_name: backend-java
    build:
      target: run
      dockerfile: backend/java/Dockerfile
    ports:
      - "8080:8080"

  backend-gleam:
    container_name: backend-gleam
    build:
      target: run
      dockerfile: backend/gleam/Dockerfile
    ports:
      - "1234:1234"