services:
  backend-go:
    container_name: backend-go
    build:
      target: run
      dockerfile: backend/go/Dockerfile
    ports:
      - "8080:8080"

  backend-java:
    container_name: backend-java
    build:
      target: run
      dockerfile: backend/java/Dockerfile
    ports:
      - "8080:8080"

  backend-gleam:
    container_name: backend-gleam
    build:
      target: run
      dockerfile: backend/gleam/Dockerfile
    ports:
      - "1234:1234"

  backend-go-test:
    container_name: backend-go-test
    build:
      target: test
      dockerfile: backend/go/Dockerfile

  mobile-react-native:
    container_name: mobile-react-native
    build:
      target: run
      dockerfile: mobile/react-native/Dockerfile

  mobile-react-native-build-apk:
    container_name: mobile-react-native-build-apk
    build:
      target: build-apk
      dockerfile: mobile/react-native/Dockerfile