name: area-prod
services:
  client_mobile:
    image: ghcr.io/epitouche/area-mobile:dev
    extends:
      file: ./docker-compose.template.yaml
      service: client_mobile

  client_web:
    image: ghcr.io/epitouche/area-frontend:dev
    extends:
      file: ./docker-compose.template.yaml
      service: client_web

  database:
    extends:
      file: ./docker-compose.template.yaml
      service: database

  server:
    image: ghcr.io/epitouche/area-backend:dev
    extends:
      file: ./docker-compose.template.yaml
      service: server

networks:
  app-networks:


volumes:
  database-data:
  shared_apk:
