definitions:
  schemas.Action:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      option:
        type: string
      service_id:
        $ref: '#/definitions/schemas.Service'
      update_at:
        type: string
    required:
    - description
    - name
    - option
    - service_id
    type: object
  schemas.Area:
    properties:
      action_id:
        $ref: '#/definitions/schemas.Action'
      action_option:
        type: string
      createdAt:
        type: string
      enable:
        type: boolean
      id:
        type: integer
      reaction_id:
        $ref: '#/definitions/schemas.Reaction'
      reaction_option:
        type: string
      update_at:
        type: string
      user_id:
        $ref: '#/definitions/schemas.User'
    required:
    - action_id
    - action_option
    - reaction_id
    - reaction_option
    - user_id
    type: object
  schemas.AuthenticationUrl:
    properties:
      authentication_url:
        type: string
    type: object
  schemas.CodeCredentials:
    properties:
      code:
        type: string
    type: object
  schemas.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  schemas.JWT:
    properties:
      token:
        type: string
    type: object
  schemas.Reaction:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      option:
        type: string
      service_id:
        $ref: '#/definitions/schemas.Service'
      update_at:
        type: string
    required:
    - description
    - name
    - option
    - service_id
    type: object
  schemas.Response:
    properties:
      message:
        type: string
    type: object
  schemas.Service:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        $ref: '#/definitions/schemas.ServiceName'
      update_at:
        type: string
    required:
    - description
    - name
    type: object
  schemas.ServiceName:
    enum:
    - spotify
    - openWeatherMap
    - timer
    - gmail
    type: string
    x-enum-varnames:
    - Spotify
    - OpenWeatherMap
    - Timer
    - Gmail
  schemas.Token:
    properties:
      createdAt:
        type: string
      expireAt:
        type: string
      id:
        type: integer
      refresh_token:
        type: string
      service_id:
        $ref: '#/definitions/schemas.Service'
      token:
        type: string
      updateAt:
        type: string
      user_id:
        $ref: '#/definitions/schemas.User'
    type: object
  schemas.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        description: can be null for Oauth2.0 users
        type: string
      token_id:
        description: Foreign key for LinkUrl
        type: integer
      updated_at:
        type: string
      username:
        type: string
    required:
    - username
    type: object
  schemas.UserAllInfo:
    properties:
      tokens:
        items:
          $ref: '#/definitions/schemas.Token'
        type: array
      user:
        $ref: '#/definitions/schemas.User'
    type: object
  schemas.UserCredentials:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /action/info/{id}:
    get:
      consumes:
      - application/json
      description: get action info of service id
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.Action'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - bearerAuth: []
      summary: get action info
      tags:
      - Action
  /area/:
    get:
      consumes:
      - application/json
      description: get user areas list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.Area'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: get user areas
      tags:
      - Area
    post:
      consumes:
      - application/json
      description: create area
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: create area
      tags:
      - Area
  /github/auth:
    get:
      consumes:
      - application/json
      description: give url to authenticate with github
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthenticationUrl'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: give url to authenticate with github
      tags:
      - Github
  /github/auth/callback:
    post:
      consumes:
      - application/json
      description: give url to authenticate with github
      parameters:
      - description: Callback Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/schemas.CodeCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.JWT'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: give url to authenticate with github
      tags:
      - Github
  /github/info/user:
    get:
      consumes:
      - application/json
      description: give user info of github
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.UserCredentials'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: give user info of github
      tags:
      - Github
  /gmail/auth:
    get:
      consumes:
      - application/json
      description: give url to authenticate with gmail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthenticationUrl'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: give url to authenticate with gmail
      tags:
      - Gmail
  /gmail/auth/callback:
    post:
      consumes:
      - application/json
      description: give url to authenticate with gmail
      parameters:
      - description: Callback Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/schemas.CodeCredentials'
      - description: Bearer token
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.JWT'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: give url to authenticate with gmail
      tags:
      - Gmail
  /gmail/info/user:
    get:
      consumes:
      - application/json
      description: give user info of gmail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.UserCredentials'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: give user info of gmail
      tags:
      - Gmail
  /ping:
    get:
      consumes:
      - application/json
      description: do ping to check if the server is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.Response'
      summary: ping example
      tags:
      - ping route
  /reaction/info/{id}:
    get:
      consumes:
      - application/json
      description: get reaction info of service id
      parameters:
      - description: Service ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.Reaction'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: get reaction info
      tags:
      - Reaction
  /service/info/:
    get:
      consumes:
      - application/json
      description: get service info of service id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.Service'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: get service info
      tags:
      - Service
  /spotify/auth:
    get:
      consumes:
      - application/json
      description: give url to authenticate with spotify
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthenticationUrl'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: give url to authenticate with spotify
      tags:
      - Spotify
  /spotify/auth/callback:
    post:
      consumes:
      - application/json
      description: give url to authenticate with spotify
      parameters:
      - description: Callback Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/schemas.CodeCredentials'
      - description: Bearer token
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.JWT'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: give url to authenticate with spotify
      tags:
      - Spotify
  /spotify/info/user:
    get:
      consumes:
      - application/json
      description: give user info of spotify
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.UserCredentials'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: give user info of spotify
      tags:
      - Spotify
  /user/info/all:
    get:
      consumes:
      - application/json
      description: give user info of user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.UserAllInfo'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: give user info of user
      tags:
      - User
  /user/info/user:
    get:
      consumes:
      - application/json
      description: give user info of user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.UserCredentials'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      security:
      - Bearer: []
      - bearerAuth: []
      summary: give user info of user
      tags:
      - User
  /user/login:
    post:
      description: Authenticates a user and provides a JWT to Authorize API calls
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.JWT'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Provides a JSON Web Token
      tags:
      - User
  /user/register:
    post:
      description: Authenticates a user and provides a JWT to Authorize API calls
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.JWT'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Provides a JSON Web Token
      tags:
      - User
securityDefinitions:
  bearerAuth:
    description: Use "Bearer <token>" as the format for the Authorization header
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
