# Push docker image to GitHub Container Registry
name: Deploy Area application on production environment

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  REPOSITORY_NAME: echo "${{ github.ref.GITHUB_REPOSITORY }}" | cut -d'/' -f2

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-mobile-image:
    runs-on: self-hosted
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      #
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: tom-mendy.com
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /tmp
            # clone the repository
            git clone git@github.com:${{ github.ref.GITHUB_REPOSITORY }}.git
            cd ${{env.REPOSITORY_NAME}}
            # login to the docker registry github
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io --username ${{ github.ref.GITHUB_ACTOR }} --password-stdin
            # run the docker-compose.prod.yml file
            echo ${{ secrets.ENV }} > .env
            sudo docker compose -f docker-compose.prod.yml up -d --force-recreate
            # cleanup
            cd /tmp
            rm -rf ${{env.REPOSITORY_NAME}}
