name: test docker

on:
  pull_request:
    branches:
      - frontend
      - mobile
      - backend
      - documentation
      - devops
      - dev
      - pre-prod
      - main
  push:
    branches:
      - frontend
      - mobile
      - backend
      - documentation
      - devops
      - dev
      - pre-prod
      - main

jobs:
  test-docker:
    runs-on: [self-hosted, docker]
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4

      - name: Set up environment
        run: cp .env.example .env

      - name: Set up mobile key
        run: |
          wget 'https://cdn.discordapp.com/attachments/1307991394203336735/1313483837032103946/area-key.jks?ex=6752efa6&is=67519e26&hm=9a8a1b1677aa00f8fb1d99c9cae016c7f05babb5f1831d6690fd2fcb5b5bed5c&' -O area-key.jks
          mv area-key.jks mobile/key/area-key.jks

      - name: Stop any running containers & remove volumes
        run: docker compose down --volumes

      - name: Run build
        run: docker compose build

      - name: Run containers
        run: docker compose up -d || docker compose logs

      - name: Stop containers
        run: docker compose down --volumes
