name: test docker

on:
  pull_request:
    branches:
      - dev
      - pre-prod
      - main
  push:
    branches:
      - dev
      - pre-prod
      - main

jobs:
  test-docker:
    runs-on: [self-hosted, docker]
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: cp .env.example .env

      - name: Stop any running containers & remove volumes
        run: docker compose down --volumes

      - name: Run build
        run: docker compose build --no-cache

      - name: Run containers
        run: docker compose up -d

      - name: Stop containers
        run: docker compose down
