name: push to mirror
run-name: push_to_mirror

on:
  push:
  pull_request:

jobs:
  push_to_mirror:
    name: push_to_mirror
    runs-on: self-hosted
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Remotes
        run: git remote -v

      - name: Add mirror remote if missing
        run: |
          if ! git remote | grep -q "mirror"; then
            git remote add mirror ${{ vars.MIRROR_URL }}
          fi
        env:
          MIRROR_URL: ${{ vars.MIRROR_URL }}

      - name: Test SSH connection
        run: ssh -T git@github.com
        env:
          GIT_SSH_COMMAND: ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

      - name: Push to mirror repository
        run: git push --mirror mirror
        env:
          GIT_SSH_COMMAND: ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
