name: Mirroring
run-name: mirroring

on:
  push:
  pull_request:
  delete:

jobs:
  push_to_mirror:
    name: push_to_mirror
    runs-on: self-hosted
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MIRROR_URL: ${{ vars.MIRROR_URL }}
        run: |
          # Set up SSH authentication
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

          # Add the mirror remote and push
          git remote add mirror ${MIRROR_URL} || true
          git push mirror --all --force
