name: Mirroring
run-name: mirroring

on:
  push:
  pull_request:

jobs:
  push_to_mirror:
    name: push_to_mirror
    runs-on: self-hosted
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: mkdir -p ~/.ssh
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - run: git remote set-url mirror ${{ vars.MIRROR_URL }}
      - run: git remote -v
      - run: git push mirror --all --force
