name: push to mirror
run-name: push_to_mirror

on:
  push:
  pull_request:

jobs:
  push_to_mirror:
    name: push_to_mirror
    runs-on: self-hosted
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure remote mirror (ensure idempotence)
        run: |
          if ! git remote | grep -q "mirror"; then
            git remote add mirror ${{ vars.MIRROR_URL }}
          fi

      - name: Push to mirror repository
        run: git push --mirror mirror
        env:
          GIT_SSH_COMMAND: ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
