name: test backend

on:
  pull_request:
    branches:
      - dev
      - backend
      - backend-feature/**
      - devops-feature/**
  push:
    branches:
      - dev
      - backend
      - backend-feature/**
      - devops-feature/**

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

defaults:
  run:
    working-directory: ./backend


jobs:
  detect-backend-golang-modules:
    name: Test Backend
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Setup env
        run: echo '${{ secrets.ENV }}' > ../.env

      - name: Run tests
        run: ./test.sh
