name: Mirroring
run-name: update-dev-base-branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  update_dev_base_branch:
    name: update_dev_base_branch
    runs-on: self-hosted
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Add the SSH key to the runner
      - run: mkdir -p ~/.ssh
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Update the backend branch of the dev branch
      - run: git switch backend
      - run: git pull origin dev
      - run: git push

      # Update the frontend branch of the dev branch
      - run: git switch frontend
      - run: git pull origin dev
      - run: git push

      # Update the mobile branch of the dev branch
      - run: git switch mobile
      - run: git pull origin dev

      # Update the documentation branch of the dev branch
      - run: git switch documentation
      - run: git pull origin dev
      - run: git push

      # Update the devops branch of the dev branch
      - run: git switch devops
      - run: git pull origin dev
      - run: git push